Import('env')
import os

WorkSpacePath = env['WorkSpace']
length = len(WorkSpacePath)
SourcePath = os.getcwd()[length:]
objects = env.Object(target = [WorkSpacePath+'/Build/obj'+SourcePath+'/startup'] , source = ['startup.c'], CPPPATH = Split(WorkSpacePath+'/Source/'))
pass
print('Compile',objects)
Return('objects')